# Generated by Django 5.1.2 on 2024-11-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMaster',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_code', models.CharField(max_length=10)),
                ('leave_description', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Leave Masters',
                'db_table': 'leave_master',
            },
        ),
        migrations.CreateModel(
            name='LeaveDetails',
            fields=[
                ('leave_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='employee.employee')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_details', to='leave_management.leavemaster')),
            ],
            options={
                'verbose_name_plural': 'Leave Details',
                'db_table': 'leave_details',
            },
        ),
    ]
