# Generated by Django 5.1.2 on 2024-11-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Designations',
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'qualifications',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pen', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=10)),
                ('password', models.CharField(default='', editable=False, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('mob_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Permanent Teaching'), (1, 'Guest Teaching'), (2, 'Non-Teaching')])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.designation')),
            ],
            options={
                'verbose_name_plural': 'employees',
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.qualification')),
            ],
            options={
                'db_table': 'employee_qualifications',
                'unique_together': {('employee', 'qualification', 'stream')},
            },
        ),
    ]
