# Generated by Django 5.1.2 on 2024-11-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.IntegerField(choices=[(0, 'Permanent Teaching'), (1, 'Guest Teaching'), (2, 'Permanent Non-Teaching'), (3, 'Temporary Non-Teaching')]),
        ),
    ]
