# Generated by Django 5.1.2 on 2024-11-02 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeedetails',
            options={'verbose_name_plural': 'Committee Details'},
        ),
        migrations.AlterModelOptions(
            name='subcommittee',
            options={'verbose_name_plural': 'Sub Committees'},
        ),
        migrations.AddField(
            model_name='committeedetails',
            name='subcommittee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committee.subcommittee'),
        ),
        migrations.AlterField(
            model_name='committeedetails',
            name='committee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='committee.committe'),
        ),
    ]
