# Generated by Django 5.1.2 on 2024-11-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committee', '0002_alter_committeedetails_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committe',
            name='order_number',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
